CXX=icpc
CXXFLAGS=-std=c++0x -g -ip -ansi-alias -O2 -tbb
#CXXFLAGS=-std=c++0x -g -ip -ansi-alias -DNVARIADIC -O2 -tbb

.PHONY: all clean

all: test1 test2 ant members inheritance nested b0nested ptest1 ittest1 utests utestsn

clean:
	rm test1 test2 ant members inheritance nested b0nested ptest1 ittest1 utests utestsn
